### ISSUE TITLE
Bug gefunden bei Save/Load

### ISSUE THREAD

**Issue by mtstar2007** [mrpatpat/Landung#1]
Nach dem Laden eines Spielstandes funktioniert der erste Zug nicht ( wenn man anfängt; gegen KI ).
Fehler tritt nur auf, wenn man den ersten Zug VOR dem Setzen abspeichert und dann wieder lädt.
Ab Zug 2 funktioniert alles wie geplant.

**Comment by mrpatpat** [comment]
erledigt
